// @ts-check

// Each section's sidebar is generated from its folder under docs/.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = Object.fromEntries(
  ['workflows', 'architecture', 'integrations', 'standards', 'implementation'].map((dir) => [
    dir,
    [{type: 'autogenerated', dirName: dir}],
  ]),
);

export default sidebars;
